apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.letsencrypt.org/directory
    email: '<email address>'
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
    #use http process of obtaining the certification